import Foundation
import PDFKit
import CoreGraphics

/// What came out of a PDF.
enum PayslipPDFOutcome {
    /// The file carried its own text. These characters are the file's, not a
    /// recogniser's opinion of them.
    case text([PayslipFragment], PayslipSource)
    /// The file is a scan. Pages rasterised, ready for `PayslipOCR`.
    case needsRecognition([CGImage])
}

/// v1.1: reading a payslip out of a PDF, text layer first.
///
/// Measured on a real Chrome-printed payslip: `page.string` returned all 1172
/// characters exactly, and OCR on the same file was unnecessary. That is the
/// good case and it is common, because most Portuguese payslips arrive by email
/// as PDFs generated by Primavera, Sage, PHC or Cegid rather than as photos.
///
/// The surprise was the geometry. `characterBounds(at:)` desynchronised from
/// `page.string`'s own indices on that same file and produced fragments like
/// "ubsidio d e f erias" that classified almost nothing, while laying the exact
/// text out from its printed line structure classified every line item
/// correctly. So the line path leads and the bounds path is the fallback,
/// which is the opposite of what it looks like it should be.
enum PayslipPDF {

    /// A payslip is one page, occasionally two when the original and the copy
    /// are bound together. Three is generous and it is also the cap that stops
    /// a two-hundred-page PDF rasterising itself into an out-of-memory crash.
    static let maximumPages = 3

    /// Long edge for a rasterised page, matching `PayslipOCR.recognitionLongEdge`
    /// so a scanned PDF and a photograph reach the recogniser at the same size
    /// and the measurement behind that number covers both.
    static let rasterLongEdge = PayslipOCR.recognitionLongEdge

    /// Below this much text on a page, there is no usable text layer.
    static let minimumCharacters = 200
    static let minimumMoneyTokens = 3

    // MARK: Entry point

    static func read(url: URL) -> Result<PayslipPDFOutcome, PayslipUnreadable> {
        let scoped = url.startAccessingSecurityScopedResource()
        defer { if scoped { url.stopAccessingSecurityScopedResource() } }

        guard let document = PDFDocument(url: url) else { return .failure(.unsupportedFile) }
        // Locked is the one that matters. An encrypted PDF we hold the empty
        // password for opens fine and is not a problem.
        if document.isEncrypted && document.isLocked { return .failure(.encryptedPDF) }
        guard document.pageCount > 0 else { return .failure(.noTextFound) }

        let pages = (0..<min(document.pageCount, maximumPages)).compactMap { document.page(at: $0) }
        guard !pages.isEmpty else { return .failure(.noTextFound) }

        if hasUsableTextLayer(pages) {
            let lines = fragments(fromLinesOf: pages)
            if carriesLabelledAmounts(lines) { return .success(.text(lines, .pdfLines)) }
            // Line order failed to pair labels with amounts. Per-character
            // geometry is worth a try before falling back to pixels.
            let bounds = fragments(fromBoundsOf: pages)
            if carriesLabelledAmounts(bounds) { return .success(.text(bounds, .pdfBounds)) }
            // Text is there but neither layout made sense of it. Still better
            // than rasterising: hand back the line version and let the reader
            // correct it on the review screen.
            return .success(.text(lines, .pdfLines))
        }

        let images = pages.compactMap { raster($0) }
        guard !images.isEmpty else { return .failure(.noTextFound) }
        return .success(.needsRecognition(images))
    }

    // MARK: The text layer

    static func hasUsableTextLayer(_ pages: [PDFPage]) -> Bool {
        let text = pages.compactMap(\.string).joined(separator: "\n")
        let alphanumerics = text.reduce(into: 0) { $0 += ($1.isLetter || $1.isNumber) ? 1 : 0 }
        guard alphanumerics >= minimumCharacters else { return false }
        let money = text
            .split(whereSeparator: { $0 == " " || $0.isNewline })
            .filter { PayslipNumber.cents(from: String($0)) != nil }
        return money.count >= minimumMoneyTokens
    }

    /// True when at least one row pairs a description with an amount. This is
    /// what separates a layout that worked from one that shredded the page.
    static func carriesLabelledAmounts(_ fragments: [PayslipFragment]) -> Bool {
        let rows = PayslipLayout.mergeOrphanRows(PayslipLayout.rows(from: fragments))
        return rows.contains { row in
            row.fragments.contains { PayslipNumber.cents(from: $0.text) != nil }
                && !PayslipLayout.label(of: row).isEmpty
        }
    }

    /// Fragments laid out from the printed line structure.
    ///
    /// x comes from the character offset within the line and y from the line
    /// number, which is synthetic geometry and perfectly good: every consumer
    /// downstream wants rows and a left-to-right order, and this gives both.
    /// Column detection is weaker than on a photograph, which is why the
    /// classifier falls back to summing by side rather than by column.
    static func fragments(fromLinesOf pages: [PDFPage]) -> [PayslipFragment] {
        var out: [PayslipFragment] = []
        let pageCount = Double(pages.count)
        for (pageIndex, page) in pages.enumerated() {
            let lines = (page.string ?? "").components(separatedBy: .newlines)
            let width = Double(max(lines.map(\.count).max() ?? 1, 1))
            let count = Double(max(lines.count, 1))
            for (lineIndex, line) in lines.enumerated() {
                // Each page gets its own vertical band, so a row on page one
                // can never merge with a row on page two.
                let y = (Double(pageIndex) + Double(lineIndex) / count) / pageCount
                let height = 0.9 / count / pageCount
                var offset = 0
                for word in line.split(separator: " ", omittingEmptySubsequences: false) {
                    if !word.isEmpty {
                        out.append(PayslipFragment(
                            text: String(word),
                            x0: Double(offset) / width,
                            x1: Double(offset + word.count) / width,
                            y0: y, y1: y + height))
                    }
                    offset += word.count + 1
                }
            }
        }
        return out
    }

    /// Fragments laid out from per-character bounds.
    ///
    /// Real geometry, when the generator provides it consistently. Words break
    /// on whitespace and on a horizontal gap wider than a fraction of the glyph
    /// HEIGHT. Height and not a running character width: measured against the
    /// width of the characters seen so far, a word starting with a narrow glyph
    /// sets too small a scale and "30.91" splits into "3" and "0.91".
    static func fragments(fromBoundsOf pages: [PDFPage]) -> [PayslipFragment] {
        var out: [PayslipFragment] = []
        let pageCount = Double(pages.count)
        for (pageIndex, page) in pages.enumerated() {
            let box = page.bounds(for: .mediaBox)
            guard box.width > 0, box.height > 0 else { continue }
            let characters = Array(page.string ?? "")
            var buffer = ""
            var rect: CGRect?

            func flush() {
                defer { buffer = ""; rect = nil }
                guard let rect, !buffer.trimmingCharacters(in: .whitespaces).isEmpty else { return }
                let top = 1 - Double((rect.maxY - box.minY) / box.height)
                let bottom = 1 - Double((rect.minY - box.minY) / box.height)
                out.append(PayslipFragment(
                    text: buffer,
                    x0: Double((rect.minX - box.minX) / box.width),
                    x1: Double((rect.maxX - box.minX) / box.width),
                    y0: (Double(pageIndex) + top) / pageCount,
                    y1: (Double(pageIndex) + bottom) / pageCount))
            }

            for index in 0..<min(page.numberOfCharacters, characters.count) {
                let character = characters[index]
                if character.isWhitespace || character.isNewline { flush(); continue }
                let bounds = page.characterBounds(at: index)
                if let current = rect {
                    let gap = bounds.minX - current.maxX
                    let scale = max(current.height, bounds.height)
                    if gap > 0.38 * scale || abs(bounds.midY - current.midY) > current.height * 0.7 {
                        flush()
                    }
                }
                buffer.append(character)
                rect = rect.map { $0.union(bounds) } ?? bounds
            }
            flush()
        }
        return out
    }

    // MARK: Rasterising a scan

    static func raster(_ page: PDFPage) -> CGImage? {
        let box = page.bounds(for: .mediaBox)
        guard box.width > 0, box.height > 0 else { return nil }
        let scale = Double(rasterLongEdge) / Double(max(box.width, box.height))
        let width = Int((Double(box.width) * scale).rounded())
        let height = Int((Double(box.height) * scale).rounded())
        guard width > 0, height > 0,
              let context = CGContext(data: nil, width: width, height: height,
                                      bitsPerComponent: 8, bytesPerRow: 0,
                                      space: CGColorSpaceCreateDeviceRGB(),
                                      bitmapInfo: CGImageAlphaInfo.noneSkipLast.rawValue)
        else { return nil }
        context.setFillColor(CGColor(red: 1, green: 1, blue: 1, alpha: 1))
        context.fill(CGRect(x: 0, y: 0, width: width, height: height))
        context.scaleBy(x: CGFloat(scale), y: CGFloat(scale))
        context.translateBy(x: -box.minX, y: -box.minY)
        page.draw(with: .mediaBox, to: context)
        return context.makeImage()
    }
}
