#!/usr/bin/env python3
"""Scores the payslip reader against a corpus whose true figures are known.

The reader has never been measured. It was built against two real payslips, both
gone from this machine by design, and the four files that make a judgement about
a page have no automated coverage at all. `verify_payslip_reader.py` covers
everything expressible as a rule restated in Python and says so itself; a
judgement cannot be checked that way, only run.

So `tools/payslip_corpus` generates payslips from the app's own TaxEngine, which
gives them the one thing a real payslip never has: an answer key. This runs the
shipping reader over them, through `tools/payslip_probe --json`, and joins the
result against that key.

WHAT THIS CANNOT TELL YOU, on its own face rather than in a footnote:

  * Nothing about whether the 2026 tax tables are right. The corpus is computed
    from TaxEngine and three checks compare against TaxEngine, so those three
    are tautological here. `verify_tax_engine.py` is what tests the tables,
    against the AT workbooks.
  * Nothing about real PDF generators. Every page here is Chrome-printed HTML,
    and Chrome is the one generator nobody's payroll department uses.
  * It OVERSTATES label coverage by construction. The vocabulary comes from
    `PayslipLexicon.matchFixtures`, so a corpus built from the lexicon's own
    words cannot discover a label the lexicon has never seen, which is the
    reader's most likely real failure.

What it does test is not circular: whether the right cents came off the page,
what the four judgement files decide, where tiering lands for a perturbation of
known size, and how the three extraction paths compare on one identical file.
And it proves the absence of the two failures that matter most, which the shared
tax model makes CLEANER rather than weaker: because the payslip and the reader
share one tax engine, a `wrong` finding on a correct page cannot be a
disagreement about tax. It can only be the reader accusing a correct payslip.

Two metrics fail this script and nothing else does:

  falseAccusations        a `wrong` finding on a page generated to be correct
  negativeFixtureLeakage  a verdict on something that is not a payslip

Everything else is a budget, printed and never a target. In particular the skip
count must never be optimised: `docs/fixtures/README.md` already argues that an
honest reading of an awkward page is worth more than a tuned reading of a
convenient one, and 24 fixtures generated by one program are 24 observations of
that program's habits.

    tools/payslip_probe/build.sh
    tools/payslip_corpus/build.sh
    .build/payslip_corpus generate --out .build/corpus
    python3 tools/score_payslip_corpus.py --corpus .build/corpus
"""

import argparse
import json
import os
import subprocess
import sys
from collections import Counter, defaultdict

PROBE = ".build/payslip_probe"
PATHS = ["lines", "bounds", "raster"]

# Worst last, so the table reads as a slope rather than as a list.
PROFILE_ORDER = [{"name": n} for n in
                 ["clean", "scan300", "photoGood", "photoTypical",
                  "photoPoor", "photoAwful"]]

# The one figure onboarding would need. Phase 2's bridge proposes
# `facts.ssBase`, because that is the figure the employer actually charged 11%
# on, it is what the reconciler already uses as the gross for every engine
# check, and it carries arithmetic provenance rather than a label's.
GROSS_FACT = "ssBase"


def run_probe(pdf, truth, path):
    ctx = truth["context"]
    cmd = [
        PROBE, pdf, "--json",
    ] + ([] if path is None else ["--path", path]) + [
        "--region", ctx["region"],
        "--months", str(int(ctx["months"])),
        "--marital", ctx["marital"],
        "--dependents", str(ctx["dependents"]),
        "--jovem", str(ctx["jovemExemption"]),
    ]
    done = subprocess.run(cmd, capture_output=True, text=True)
    if done.returncode != 0:
        return {"outcome": "probeFailed",
                "reason": (done.stderr or done.stdout or "").strip()[:200]}
    try:
        return json.loads(done.stdout)
    except json.JSONDecodeError:
        return {"outcome": "probeFailed", "reason": "output was not json"}


def fact_cents(result, name):
    fact = (result.get("facts") or {}).get(name)
    return fact["cents"] if fact else None


def onboarding_outcome(result, truth):
    """Right to the cent, or visibly not. The metric that decides whether a
    payslip may fill in somebody's salary.

    Silent-wrong is the only unacceptable cell. The typed number has one
    property a read one cannot: the reader knows what they typed. Every figure
    the app draws is a pure function of that one number, so a gross wrong by ten
    percent is wrong on every screen for ever, with no error and no crash, and
    nobody has any reason to doubt it because they never saw a number to check.
    """
    want = truth["onboarding"]["monthlyGrossCents"]
    if result.get("outcome") != "ok":
        return "wrongVisible"          # unreadable: the reader is told, and types it
    got = fact_cents(result, GROSS_FACT)
    reviewed = bool(result.get("needsReview"))
    if got is None:
        return "wrongVisible"          # nothing offered, so nothing to accept
    if got == want:
        return "exactReviewed" if reviewed else "exactSilent"
    return "wrongVisible" if reviewed else "wrongSilent"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", default=".build/corpus")
    ap.add_argument("--paths", default=",".join(PATHS))
    ap.add_argument("--only")
    ap.add_argument("--photos", action="store_true",
                    help="score the degraded images instead of the PDFs")
    args = ap.parse_args()

    if not os.path.exists(PROBE):
        sys.exit("no %s. Run tools/payslip_probe/build.sh first." % PROBE)
    manifest_path = os.path.join(args.corpus, "manifest.json")
    if not os.path.exists(manifest_path):
        sys.exit("no %s. Run tools/payslip_corpus/build.sh then generate." % manifest_path)

    if args.photos:
        photos_path = os.path.join(args.corpus, "photos.json")
        if not os.path.exists(photos_path):
            sys.exit("no %s. Run `payslip_corpus photos` first." % photos_path)
        with open(photos_path) as fh:
            shots = json.load(fh)["photos"]
        if args.only:
            shots = [p for p in shots if p["id"] == args.only]
        # Each profile is scored as its own "path", because a photograph taken
        # badly and one taken well are different inputs, not the same input
        # measured twice.
        entries = [{"id": p["id"], "truth": p["truth"], "pdf": p["file"],
                    "profile": p["profile"]} for p in shots]
        paths = [None]
    else:
        with open(manifest_path) as fh:
            manifest = json.load(fh)
        entries = manifest["fixtures"]
        if args.only:
            entries = [e for e in entries if e["id"] == args.only]
        paths = [p.strip() for p in args.paths.split(",") if p.strip()]

    false_accusations = []
    leakage = []
    onboarding = defaultdict(Counter)
    skips = defaultdict(Counter)
    concept_tally = defaultdict(Counter)
    detection = []
    rows = []
    proposals = defaultdict(Counter)
    bad_proposals = []

    for entry in entries:
        with open(os.path.join(args.corpus, entry["truth"])) as fh:
            truth = json.load(fh)
        pdf = os.path.join(args.corpus, entry.get("pdf", ""))
        if not entry.get("pdf") or not os.path.exists(pdf):
            continue

        for path in paths:
            result = run_probe(pdf, truth, path)
            label = entry.get("profile") or path
            verdict = result.get("verdict") or {}
            findings = verdict.get("findings") or []
            not_checked = verdict.get("notChecked") or []
            injected = truth.get("injection")

            # --- the two that fail this script ---------------------------
            if truth["isPayslip"] and not injected:
                for f in findings:
                    if f["tier"] == "wrong":
                        false_accusations.append((truth["id"], label, f))
            if not truth["isPayslip"] and findings:
                leakage.append((truth["id"], label, len(findings)))

            # --- budgets --------------------------------------------------
            if truth["isPayslip"]:
                # Only on pages generated to be correct. On an INJECTED page the
                # figure printed is deliberately not the engine's, and a reader
                # that reproduces what the page says has done its job: if the
                # payslip says 2 400,02 then that is what the employer used, and
                # the inconsistency is the checker's business, not the prefill's.
                # Scoring those as "wrong gross" measured the wrong thing.
                outcome = (onboarding_outcome(result, truth)
                           if not injected else "notScored")
                if outcome != "notScored":
                    onboarding[label][outcome] += 1
                for s in not_checked:
                    skips[label][s["check"] + " / " + s["reason"]] += 1

                for concept, want in truth["concepts"].items():
                    if concept not in ("ssBase", "totalEarnings", "totalDeductions",
                                       "netPay", "employeeSS", "irs"):
                        continue
                    got = fact_cents(result, "ssContribution" if concept == "employeeSS"
                                     else concept)
                    if got is None:
                        concept_tally[concept][label + ":missing"] += 1
                    elif got == want:
                        concept_tally[concept][label + ":exact"] += 1
                    else:
                        concept_tally[concept][label + ":off"] += 1

                rows.append((truth["id"], label, result, truth, outcome))

            # What PayslipSalary would hand onboarding or the results screen.
            # It never reads the context, so this is the same in both places.
            if truth["isPayslip"]:
                p = result.get("proposal") or {}
                if p.get("outcome") == "proposal":
                    if injected:
                        proposals[label]["notScored"] += 1
                    elif p["monthlyGrossCents"] == truth["onboarding"]["monthlyGrossCents"]:
                        proposals[label]["correct"] += 1
                    else:
                        proposals[label]["WRONG"] += 1
                        bad_proposals.append((truth["id"], label,
                                              p["monthlyGrossCents"],
                                              truth["onboarding"]["monthlyGrossCents"]))
                elif p.get("outcome") == "cannot":
                    # An injected page refusing is the design working, not a
                    # refusal rate: the figure it would have rested on is the
                    # one that was deliberately moved.
                    proposals[label]["notScored" if injected
                                     else "refused:" + p["refusal"]] += 1
                else:
                    proposals[label]["neverGotThatFar"] += 1

            if injected and injected["kind"] == "line":
                flagged = [f for f in findings if f["tier"] != "correct"]
                named = [f for f in flagged if injected["concept"] in (f.get("basis") or [])]
                detection.append((truth["id"], label, injected["deltaCents"],
                                  bool(flagged), [f["check"] for f in flagged],
                                  bool(named)))

    # ---------------------------------------------------------------- output
    print("=" * 78)
    print("PAYSLIP CORPUS  %d fixture(s) x %d path(s)" % (len(entries), len(paths)))
    print("=" * 78)

    print("\n---- per fixture, per path " + "-" * 51)
    print("  %-24s %-7s %-9s %-8s %5s %5s %5s %5s" %
          ("fixture", "path", "source", "review", "wrng", "ment", "corr", "skip"))
    for fid, path, result, truth, outcome in rows:
        v = result.get("verdict") or {}
        print("  %-24s %-7s %-9s %-8s %5s %5s %5s %5s   %s" % (
            fid, path, result.get("source", result.get("outcome", "-")),
            str(result.get("needsReview", "-")),
            v.get("wrong", "-"), v.get("mentions", "-"),
            v.get("correct", "-"), v.get("notCheckedCount", "-"), outcome))

    labels = ([p["name"] for p in PROFILE_ORDER if p["name"] in onboarding]
              if args.photos else paths)
    labels = labels or sorted(onboarding)

    print("\n---- the gross onboarding would use " + "-" * 42)
    print("  the only unacceptable cell is wrongSilent\n")
    print("  %-8s %12s %14s %13s %12s" % ("path", "exactSilent", "exactReviewed",
                                          "wrongVisible", "wrongSilent"))
    for path in labels:
        c = onboarding[path]
        print("  %-8s %12d %14d %13d %12d" % (
            path, c["exactSilent"], c["exactReviewed"],
            c["wrongVisible"], c["wrongSilent"]))

    print("\n---- figures recovered, by concept " + "-" * 43)
    for concept in sorted(concept_tally):
        c = concept_tally[concept]
        cells = "  ".join("%s %d/%d/%d" % (p, c[p + ":exact"], c[p + ":off"],
                                           c[p + ":missing"]) for p in labels)
        print("  %-16s %s" % (concept, cells))
    print("  (exact/off/missing)")

    print("\n---- the salary PayslipSalary would propose " + "-" * 34)
    print("  refusing costs one tap on 'type it myself'. Proposing a wrong figure")
    print("  costs every number in the app, so WRONG is the column that matters.\n")
    reasons = sorted({k for c in proposals.values() for k in c if k.startswith("refused:")})
    print("  %-14s %8s %7s %s" % ("input", "correct", "WRONG",
                                  "  ".join(r.split(":")[1][:18] for r in reasons)))
    for path in labels:
        c = proposals[path]
        cells = "  ".join("%-18d" % c[r] for r in reasons)
        print("  %-14s %8d %7d %s" % (path, c["correct"], c["WRONG"], cells))

    if detection:
        print("\n---- injected errors, detection " + "-" * 46)
        print("  a delta inside PayslipTiering.roundingCents (2c) is SUPPOSED to go")
        print("  unflagged: rounding may never become an accusation\n")
        for fid, path, delta, flagged, checks, named in detection:
            expected = abs(delta) > 2
            if flagged == expected:
                mark = "flagged" if flagged else "quiet, as designed"
            else:
                mark = "MISSED" if expected else "flagged a rounding delta"
            print("  %-20s %-7s %+8dc  %-24s %s" % (
                fid, path, delta, mark, ",".join(sorted(set(checks))) or "-"))

    print("\n---- checks that did not run " + "-" * 48)
    print("  a budget, never a target: an honest skip beats a tuned reading\n")
    for path in labels:
        if not skips[path]:
            continue
        print("  %s:" % path)
        for key, n in sorted(skips[path].items(), key=lambda kv: (-kv[1], kv[0])):
            print("    %3d  %s" % (n, key))

    print("\n" + "=" * 78)
    failed = False
    if false_accusations:
        failed = True
        print("FALSE ACCUSATIONS: %d" % len(false_accusations))
        print("  A page generated to be correct was called wrong. The corpus and the")
        print("  reader share one tax engine, so this cannot be a disagreement about tax.")
        for fid, path, f in false_accusations:
            print("    %s [%s] %s expected=%s actual=%s delta=%s" % (
                fid, path, f["check"], f["expectedCents"],
                f["actualCents"], f["deltaCents"]))
    else:
        print("false accusations       0")

    if leakage:
        failed = True
        print("NEGATIVE FIXTURE LEAKAGE: %d" % len(leakage))
        print("  Something that is not a payslip produced a verdict.")
        for fid, path, n in leakage:
            print("    %s [%s] %d finding(s)" % (fid, path, n))
    else:
        print("negative leakage        0")

    if bad_proposals:
        failed = True
        print("WRONG SALARY PROPOSED: %d" % len(bad_proposals))
        print("  A figure that is not the gross was offered as one.")
        for fid, path, got, want in bad_proposals:
            print("    %s [%s] proposed %d, truth %d" % (fid, path, got, want))
    else:
        print("wrong salaries proposed 0")

    # A gross that was wrong and never shown is the one outcome the promotion
    # decision cannot survive, so it fails the script like the other three
    # rather than being printed and hoped about.
    silent = sum(onboarding[p]["wrongSilent"] for p in labels)
    if silent:
        failed = True
        print("SILENT-WRONG GROSSES: %d" % silent)
        print("  A wrong gross was recovered and the reader would never have been")
        print("  shown it. Every figure the app draws is a pure function of that one.")
        for fid, path, result, truth, outcome in rows:
            if outcome == "wrongSilent":
                print("    %s [%s]" % (fid, path))
    else:
        print("silent-wrong grosses    0")
    print("=" * 78)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
